# Generated by Django 5.0.4 on 2024-06-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Name',
            new_name='name',
        ),
    ]
