# Generated by Django 5.0.4 on 2024-07-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_item_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dateofbirth',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
