# Generated by Django 5.0.4 on 2024-07-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_item_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dateofbirth',
            field=models.DateField(default=''),
        ),
    ]
