# Generated by Django 5.0.4 on 2024-07-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_item_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='placeofbirth',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
