# Generated by Django 5.0.4 on 2024-07-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_item_placeofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='placeofbirth',
            field=models.CharField(max_length=100),
        ),
    ]
