# Generated by Django 5.0.4 on 2024-07-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_item_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='dateofbirth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='placeofbirth',
            new_name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sex',
        ),
    ]
