# Generated by Django 5.0.4 on 2024-07-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_item_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sex',
            field=models.CharField(max_length=100),
        ),
    ]
