# Generated by Django 5.0.4 on 2024-07-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_item_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
