# Generated by Django 5.0.4 on 2024-07-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_item_barangay_item_city_municipality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='mother_maiden_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
