# Generated by Django 5.0.4 on 2024-07-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_item_mother_maiden_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='TItenichrom',
            field=models.CharField(default='maliit', max_length=255),
        ),
    ]
